### ISSUE TITLE
Neoterm shows in buffer list

### ISSUE THREAD

**Issue by cjnucette** [itmecho/neoterm.nvim#2]
When you open or toggle a neoterm it shows in the buffer list. This is a little inconvenience because I use a buffertabline plugin and it shows there. Is there a way to hide it?

**Comment by itmecho** [comment]
Hmm this wasn't the intended behaviour! I've fixed it so that the buffer isn't listed now. If you could update and confirm that it's working as expected, I'll close the issue

**Comment by cjnucette** [comment]
Yes it's fixed, thank you.
