### ISSUE TITLE
Automatically hide terminal on exiting terminal mode

### ISSUE THREAD

**Issue by LordMZTE** [itmecho/neoterm.nvim#4]
I think it would be really handy to have the option to make a terminal close automatically once the terminal mode is exited. That way, if only one command should be ran, there'd be no need to manually toggle the terminal again, and it will simply hide once terminal mode is exited.

**Comment by itmecho** [comment]
Can you clarify exactly what you mean? Do you mean that once the command you sent with `NeotermRun` finishes, automatically hide the terminal window, or do you mean when the terminal exits, i.e. typing `exit` in the terminal?

**Comment by LordMZTE** [comment]
When neoterm is toggled, nvim will go into terminal mode (basically insert mode for terminals). If the user goes back to normal mode, the buffer will stay visible. My suggestion is that the buffer will be hidden instead.

**Comment by itmecho** [comment]
So you're in terminal mode and you hit `<C-\><C-n>` and you'd like that to toggle the Neoterm window?

**Comment by LordMZTE** [comment]
Exactly!

**Comment by itmecho** [comment]
OK, I've just pushed a commit that triggers custom autocommands which you should be able to use to achieve what you want! You should just need to add something like this:

```vim
autocmd User NeotermTermLeave NeotermClose
```

or
```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "NeotermTermLeave",
  callback = require('neoterm').close,
})
```

Let me know if that works!

**Comment by LordMZTE** [comment]
Works perfectly!
